name: Build scrapper

on:
  pull_request:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'link-parser/**'
      - '.github/workflows/scrapper.yml'
  push:
    branches:
      - 'main'
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'link-parser/**'
      - '.github/workflows/scrapper.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/aslugin/scrapper:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Jooq codegen run
        run: mvn package -pl scrapper-jooq -am && java -jar scrapper-jooq/target/scrapper-jooq-1.0-SNAPSHOT.jar

      - name: Scrapper Maven Package
        run: mvn package -pl scrapper -am

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_NAME }} ./scrapper/

      - name: Push image to container registry
        run: docker push ${{ env.IMAGE_NAME }}

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Check style
        run: mvn -pl scrapper -am checkstyle:check
